### PR TITLE
Silence warnings for fields with no getters

### PR DESCRIPTION
**Pull request by rsandell**
### Testing done

```[tasklist]
### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Review by raul-arabaolaza — APPROVED** [review]

**Comment by rsandell** [comment]
@amuniz are you able to merge and release this please?

**Comment by amuniz** [comment]
Sure. What warnings is this fixing BTW?

**Comment by rsandell** [comment]
There are sporadic system log serialization warnings about the class because of the missing getters.

**Comment by rsandell** [comment]
@amuniz Thanks for the merge! But this PR needs a significant label for the release to happen. :pray:

**Comment by amuniz** [comment]
@rsandell added. However I can't trigger the release pipeline manually, do you know of some way to trigger a release?

**Comment by rsandell** [comment]
https://github.com/jenkinsci/aws-credentials-plugin/actions/workflows/cd.yaml

**Comment by rsandell** [comment]
There should be a "Run Workflow button" somewhere there

**Pull request merged**
