### PR TITLE
Add support for assuming IAM roles

### PR DESCRIPTION
**Pull request by mattstep**
@reviewbybees

### CODE REVIEW

**Comment by recampbell** [comment]
@stephenc Do you mind taking a peek for any issues here?

**Comment by stephenc** [comment]
:bee: from the 😎 on a 🏇

**Comment by stephenc** [comment]
@mattstep often reviews are from the proverbial "blind person on a galloping horse"... 😎 on a 🏇 is the emoji equivalent

**Comment by mattstep** [comment]
@stephenc Ah, gotcha!

**Comment by mattstep** [comment]
@recampbell or @stephenc can I get this merged? It meets the requirements of reviewbybees I believe...

**Comment by cristim** [comment]
How are these roles exposed to Jenkins?

In my setup the plugin only defines the access key and secret variables and fails to expose the temporary token to the Jenkins job, which fails to run.

**Comment by recena** [comment]
Changes without JIRA issue associated... 😢

**Comment by farrellit** [comment]
I don't understand either.  It says it "supports roles" but there doesn't seem to be any way to get the session token.  What a waste of time this plugin has turned into for me!

**Pull request merged**
