### PR TITLE
Expose method through interface for getting credentials with MFA toke…

### PR DESCRIPTION
**Pull request by mattstep**
…n passed in

@reviewbybees

### CODE REVIEW

**Comment by mattstep** [comment]
@stephenc can you ptal?

**Comment by recampbell** [comment]
🐝

**Comment by andresrc** [comment]
Adding a new method to an interface is a binary-incompatible change. The only implementation of the interface I've found (in the jenkinsci org) is in this same plugin, but it may break other implementations if any. 

We would like to tag this incompatible change someway, wouldn't we?

**Comment by mattstep** [comment]
@andresrc Happy to tag it, is there a common way in the jenkins community to do this? I'll dig around for an annotation...

**Comment by andresrc** [comment]
No other implementation found, merging.

**Comment by jglick** [comment]
AFAICT this API has never been used in a released plugin, only in experimental code subsequently discarded, so it could be deprecated.

**Pull request merged**
